### ISSUE TITLE
Changing mouse cursor during measurement

### ISSUE THREAD

**Issue by mahmoudmy** [ljagis/leaflet-measure#28]
Hello every body!
I think the mouse cursor on map isn't proper when the measurement control is active.
So I tried to change it:
```CSS
.layer-measuredrag {
  cursor: crosshair !important;
}
```
But it doesn't work! Any idea?
